#!/bin/bash

# Sweat24 Admin Panel Deployment Script
# Usage: ./deploy.sh [version]
# Example: ./deploy.sh v1.2

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}🚀 Sweat24 Admin Panel Deployment Script${NC}"
echo "=========================================="

# Get version parameter or auto-increment
if [ -n "$1" ]; then
    NEW_VERSION="$1"
    echo -e "${BLUE}📝 Using provided version: ${GREEN}$NEW_VERSION${NC}"
else
    # Auto-increment version
    CURRENT_VERSION=$(grep 'APP_VERSION = ' src/config/version.ts | sed 's/.*"v\([0-9]*\.[0-9]*\)".*/\1/')
    MAJOR=$(echo $CURRENT_VERSION | cut -d. -f1)
    MINOR=$(echo $CURRENT_VERSION | cut -d. -f2)
    NEW_MINOR=$((MINOR + 1))
    NEW_VERSION="v$MAJOR.$NEW_MINOR"
    echo -e "${BLUE}📈 Auto-incrementing version: ${GREEN}$NEW_VERSION${NC}"
fi

# Update version file
echo -e "${BLUE}📝 Updating version configuration...${NC}"
BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%S.000Z")
BUILD_ID=$(openssl rand -hex 3)

cat > src/config/version.ts << EOF
// Version configuration
// Updated automatically by deploy script
export const APP_VERSION = "$NEW_VERSION";

// Deploy info (auto-generated by deploy script)
export const BUILD_DATE = "$BUILD_DATE";
export const BUILD_ID = "$BUILD_ID";
EOF

echo -e "${GREEN}✅ Version updated to $NEW_VERSION${NC}"

# Build the application
echo -e "${BLUE}🔨 Building application...${NC}"
npm run build

if [ $? -eq 0 ]; then
    echo -e "${GREEN}✅ Build completed successfully${NC}"
else
    echo -e "${RED}❌ Build failed${NC}"
    exit 1
fi

# Commit changes if git is available
if command -v git &> /dev/null && [ -d ".git" ]; then
    echo -e "${BLUE}📦 Committing version update...${NC}"
    git add src/config/version.ts
    git commit -m "bump: version $NEW_VERSION" || echo "No changes to commit"
    echo -e "${GREEN}✅ Version committed${NC}"
fi

echo ""
echo -e "${GREEN}🎉 Deployment completed successfully!${NC}"
echo -e "${BLUE}📊 Deploy Summary:${NC}"
echo "   Version: $NEW_VERSION"
echo "   Build Date: $BUILD_DATE"
echo "   Build ID: $BUILD_ID"
echo ""
echo -e "${YELLOW}💡 The version indicator will show '$NEW_VERSION' in the admin panel${NC}"
