// Version configuration
// Updated automatically by deploy script
export const APP_VERSION = "v1.17";

// Deploy info (auto-generated by deploy script)
export const BUILD_DATE = "2025-08-19T13:41:59.000Z";
export const BUILD_ID = "b09712";
