// Version configuration
// Updated automatically by deploy script
export const APP_VERSION = "v1";

// Deploy info (auto-generated by deploy script)
export const BUILD_DATE = "2025-08-18T13:16:39.000Z";
export const BUILD_ID = "aab468";
