// Version configuration
// Updated automatically by deploy script
export const APP_VERSION = "v1.20";

// Deploy info (auto-generated by deploy script)
export const BUILD_DATE = "2025-08-20T13:13:31.000Z";
export const BUILD_ID = "fc5043";
